### ISSUE TITLE
Problem with receiving notifications.

### ISSUE THREAD

**Issue by tl87** [denisgolius/zabbix-to-gotify-alert#4]
Hello,

I'm having problems with receiving notifications from Zabbix in Gotify.

I've followed your helpful guide, and when testing in Zabbix GUI i see `Media type test successful.`, but nothing shows up in Gotify.

I have made sure that Zabbix can reach Gotify on the network:

```bash
# nc -vz -w 5 192.168.20.14 8081
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.20.14:8081.
Ncat: 0 bytes sent, 0 bytes received in 0.02 seconds.
```

Gotify IP is `192.168.20.14`.
Gotify Port is `8081`.

It works as expected when using the `gotify.sh` script from the Zabbix server via CLI:

```bash
# bash -x gotify.sh "xxxxxxxx" "test" "test" "1"
+ GOTIFY_URL=http://192.168.20.14:8081
+ GOTIFY_TOKEN=xxxxxxxx
+ SUBJECT=test
+ MESSAGE=test
+ SEVERITY=1
+ case $SEVERITY in
+ PRIORITY=1
+ curl -X POST 'http://192.168.20.14:8081/message?token=xxxxxxxx' -F title=test -F message=test -F priority=1
{"id":8,"appid":5,"message":"test","title":"test","priority":1,"date":"2024-12-09T08:48:25.035426196Z"}
```

![gotify_success](https://github.com/user-attachments/assets/bcbc5513-d335-4d5c-8e0c-62c795cdcf33)

That tell's me that the error is somewhere in the Zabbix webinterface.

### Media Type:

![mediatype](https://github.com/user-attachments/assets/98c7b07e-b7b5-41ee-a730-57250d124e03)

### Script is available for Zabbix:

```bash
# docker exec -it zabbix-server ls /usr/lib/zabbix/alertscripts/
gotify.sh  mattermost.py
```

### Media added to Zabbix user:

![users](https://github.com/user-attachments/assets/1540179a-9a3a-4e8b-b332-b8e0232306b0)

Do you have any idea to what I' missing or doing wrong? Any pointers would be helpful. Thanks :-)

**Comment by tl87** [comment]
It seems to be working, but when trying to test from the Zabbix Web Interface, it does not work, but getting a real alert, will trigger a notification to Gotify... strange..

**Comment by denisgolius** [comment]
Hey @tl87 , checkout https://github.com/denisgolius/zabbix-to-gotify-alert/pull/2 also. Seem like the author don't want to write the documentation but if this proposal will work for you. than you may send a new PR with a description.

**Comment by tl87** [comment]
@denisgolius, thank for sharing 👍🏻

**Comment by williamdes** [comment]
> Hey @tl87 , checkout #2 also. Seem like the author don't want to write the documentation but if this proposal will work for you. than you may send a new PR with a description.

It is not exactly that I do not want but sure is someone has an idea to present it nicely go ahead.
This year I had too much work, maybe next year I can try to make my PR up to standards
